baseURL = "https://gopher-cn.icu"
title = "‰∫ëÁöÑÂçöÂÆ¢"

theme = "hugo-coder"

languageCode = "zh"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences =     true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "üåà‰∫ë‚òÅÔ∏è"
    description = "Cloud's personal website"
    keywords = "blog,developer,personal"
    info = "Code lover & Guitar lover"
    avatarURL = "images/avatar1.jpg"

    dateFormat = "January 2, 2006"

    hideFooter = true
    hideCredits = false
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/yunteng9345/blog/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/yunteng9345/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/yunteng95"

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "ÊñáÁ´†"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "ÂÖ≥‰∫é"
            weight = 2
            url = "about/"

            [[languages.en.menu.main]]
            name = "È°πÁõÆ"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "ËÅîÁ≥ªÊàë"
            weight = 6
            url = "contact/"